scan_timeout = 20
add_newline = false

[character]
success_symbol = " ❤ (bold #00A652)"
error_symbol = " ✖ (bold #df382c)"

[cmd_duration]
min_time = 50

[directory]
truncation_length = 10
truncate_to_repo = false
format = "[$path](bold italic #87A752) [$read_only](bold italic red) "

[hostname]
ssh_only = false
format = "⟪$hostname⟫(bold italic #87A752) "

[nix_shell]
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
format = 'via [❄️ $state( \($name\))](bold blue) '

[python]
pyenv_version_name = true

[time]
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = true

[status]
disabled = false
