[character]
use_symbol_for_status = true  # Show "✖" when the command faild
symbol = "➟"     # The "symbol" segment is being set to "➜"
error_symbol = "✗"
style_success = "bold #00A652"
style_failure = "bold #df382c"

[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
prefix = "️"
style = "bold italic #87A752"

[hostname]
ssh_only = false
prefix = "️"
disabled = false
style = "bold italic #87A752"

[time]
format = "%T"
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false

