
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

# options
unsetopt share_history

# aliases
alias dockerprune="sudo docker system prune -af --volumes"
alias c="cargo"
alias cat="bat"
alias du="dust"
alias e="emacs"
alias em="emacs (fzf --height=15 --reverse)"
alias f="fzf"
alias find="fd"
alias grep="rg"
alias ls="exa"
alias x="exa"
alias ps="procs"
alias sed="sd"
alias top="ytop"

eval "$(direnv hook zsh)" 
eval "$(starship init zsh)"