
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

unsetopt share_history

eval "$(direnv hook zsh)" 
eval "$(starship init zsh)"